<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ville extends \AppBundle\Entity\Ville implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'departement', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'slug', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'nom', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'nomSimple', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'nomReel', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'nomSoundex', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'codePostal', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'commune', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'codeCommune', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'arrondissement', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'canton', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'amdi', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'longitudeDeg', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'latitudeDeg', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'longitudeGrd', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'latitudeGrd', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'longitudeDms', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'latitudeDms', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'zmin'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'departement', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'slug', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'nom', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'nomSimple', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'nomReel', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'nomSoundex', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'codePostal', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'commune', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'codeCommune', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'arrondissement', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'canton', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'amdi', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'longitudeDeg', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'latitudeDeg', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'longitudeGrd', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'latitudeGrd', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'longitudeDms', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'latitudeDms', '' . "\0" . 'AppBundle\\Entity\\Ville' . "\0" . 'zmin'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ville $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartement($departement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartement', [$departement]);

        return parent::setDepartement($departement);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartement', []);

        return parent::getDepartement();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomSimple($nomSimple)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomSimple', [$nomSimple]);

        return parent::setNomSimple($nomSimple);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomSimple()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomSimple', []);

        return parent::getNomSimple();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomReel($nomReel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomReel', [$nomReel]);

        return parent::setNomReel($nomReel);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomReel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomReel', []);

        return parent::getNomReel();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomSoundex($nomSoundex)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomSoundex', [$nomSoundex]);

        return parent::setNomSoundex($nomSoundex);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomSoundex()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomSoundex', []);

        return parent::getNomSoundex();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostal($codePostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostal', [$codePostal]);

        return parent::setCodePostal($codePostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostal', []);

        return parent::getCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommune($commune)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommune', [$commune]);

        return parent::setCommune($commune);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommune()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommune', []);

        return parent::getCommune();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeCommune($codeCommune)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeCommune', [$codeCommune]);

        return parent::setCodeCommune($codeCommune);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeCommune()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeCommune', []);

        return parent::getCodeCommune();
    }

    /**
     * {@inheritDoc}
     */
    public function setArrondissement($arrondissement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArrondissement', [$arrondissement]);

        return parent::setArrondissement($arrondissement);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrondissement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrondissement', []);

        return parent::getArrondissement();
    }

    /**
     * {@inheritDoc}
     */
    public function setCanton($canton)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCanton', [$canton]);

        return parent::setCanton($canton);
    }

    /**
     * {@inheritDoc}
     */
    public function getCanton()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCanton', []);

        return parent::getCanton();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmdi($amdi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmdi', [$amdi]);

        return parent::setAmdi($amdi);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmdi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmdi', []);

        return parent::getAmdi();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitudeDeg($longitudeDeg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitudeDeg', [$longitudeDeg]);

        return parent::setLongitudeDeg($longitudeDeg);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitudeDeg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitudeDeg', []);

        return parent::getLongitudeDeg();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitudeDeg($latitudeDeg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitudeDeg', [$latitudeDeg]);

        return parent::setLatitudeDeg($latitudeDeg);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitudeDeg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitudeDeg', []);

        return parent::getLatitudeDeg();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitudeGrd($longitudeGrd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitudeGrd', [$longitudeGrd]);

        return parent::setLongitudeGrd($longitudeGrd);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitudeGrd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitudeGrd', []);

        return parent::getLongitudeGrd();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitudeGrd($latitudeGrd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitudeGrd', [$latitudeGrd]);

        return parent::setLatitudeGrd($latitudeGrd);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitudeGrd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitudeGrd', []);

        return parent::getLatitudeGrd();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitudeDms($longitudeDms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitudeDms', [$longitudeDms]);

        return parent::setLongitudeDms($longitudeDms);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitudeDms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitudeDms', []);

        return parent::getLongitudeDms();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitudeDms($latitudeDms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitudeDms', [$latitudeDms]);

        return parent::setLatitudeDms($latitudeDms);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitudeDms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitudeDms', []);

        return parent::getLatitudeDms();
    }

    /**
     * {@inheritDoc}
     */
    public function setZmin($zmin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZmin', [$zmin]);

        return parent::setZmin($zmin);
    }

    /**
     * {@inheritDoc}
     */
    public function getZmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZmin', []);

        return parent::getZmin();
    }

}
